version: "3"
services:
  dns:
    build: .
    restart: on-failure
    ports:
      - "53:53/udp"
    environment:
      # The domain name under which Backname will be running (real-world example: backname.io)
      - ZONE
      # The public IPv4 address of this server hosting Backname (in a dual-server setup, two comma-separated addresses)
      - NAMESERVER_A
      # Optional: The public IPv6 address of this server hosting Backname, if supporting IPv6 (in a dual-server setup, two comma-separated addresses)
      - NAMESERVER_AAAA
      # Optional: Website A and/or AAAA records that will be served for your-backname-domain.com + www.your-backname-domain.com (comma-separated)
      - WEBSITE_A
      - WEBSITE_AAAA
      # Optional: TXT record values server at the root of the zone (comma-separated), if needed for e.g. domain verification
      - ROOT_TXT
      # Optional: IP addresses blocked from receiving a backname (comma-separated), if seeing problematic usage
      - BLOCKLIST
